# Generated by Django 3.1.4 on 2020-12-26 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201226_1059'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
