# Generated by Django 3.1.6 on 2021-02-06 13:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_modificado', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('marca', models.TextField(max_length=100, verbose_name='Marca do carro')),
                ('ano', models.PositiveIntegerField(verbose_name='Ano')),
                ('cor', models.CharField(max_length=10)),
                ('combustivel', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
